# Generated by Django 4.0.4 on 2022-04-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='posicao',
            field=models.CharField(choices=[('e', 'Esquerda'), ('d', 'Direita')], default='e', max_length=1, verbose_name='Posição'),
        ),
    ]
